# Generated by Django 4.1.1 on 2022-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25, null=True)),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(default='test@test.test', max_length=25)),
                ('password', models.CharField(default='testtest', max_length=25)),
                ('password_updated_at', models.DateField(null=True)),
                ('profile_image', models.URLField(null=True)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
