# Generated by Django 4.1.1 on 2022-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentications', '0006_alter_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='test@test.test', max_length=25, unique=True),
        ),
    ]
