# Generated by Django 4.1.1 on 2022-10-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentications', '0008_user_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
