# Generated by Django 4.1.7 on 2023-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(default="", null=True, upload_to="apis/images"),
        ),
    ]
