# Generated by Django 4.1.1 on 2022-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='test_user',
                                   max_length=25, unique=True),
        ),
    ]
