# Generated by Django 4.1.1 on 2022-12-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_garden_created_at_garden_updated_at_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
