# Generated by Django 4.1.2 on 2023-02-03 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_nickname'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='photo',
        #     name='photoUrl',
        # ),
        # migrations.AddField(
        #     model_name='photo',
        #     name='image',
        #     field=models.ImageField(default='', upload_to='accounts/images'),
        # ),
        # migrations.AddField(
        #     model_name='photo',
        #     name='slug',
        #     field=models.SlugField(default='', verbose_name=str),
        # ),
        migrations.AlterField(
            model_name='garden',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL),
        ),
    ]
