# Generated by Django 4.1.2 on 2023-01-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="isMainPhoto",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="photo",
            name="season",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Printemps"), (1, "Été"), (2, "Automne"), (3, "Hiver")],
                null=True,
            ),
        ),
    ]
