# Generated by Django 4.1.2 on 2023-01-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photoUrl',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='', upload_to='accounts/images'),
        ),
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(default='', verbose_name=str),
        ),
    ]
