# Generated by Django 4.1.7 on 2023-06-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='senderd',
            new_name='sender',
        ),
    ]
