# Generated by Django 4.1.7 on 2023-03-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(default="", upload_to="apis/images"),
        ),
    ]
