# Generated by Django 4.1.7 on 2023-06-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_senderd_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversationd',
            new_name='conversation',
        ),
    ]
