# Generated by Django 4.1.7 on 2023-05-19 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_conversation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 14, 24, 39, 444923, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 14, 24, 39, 444928, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 14, 24, 39, 444487, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='garden',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 14, 24, 39, 444620, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 14, 24, 39, 445197, tzinfo=datetime.timezone.utc)),
        ),
    ]
